# Generated by Django 4.0.4 on 2022-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=100, upload_to='edu'),
            preserve_default=False,
        ),
    ]
