# Generated by Django 4.0.4 on 2022-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
