# Generated by Django 4.0.4 on 2022-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
