# Generated by Django 4.0.4 on 2022-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_homework_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
