# Generated by Django 4.0.4 on 2022-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_alter_homework_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
