# Generated by Django 4.0.4 on 2022-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_alter_homework_description_alter_homework_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_to_send',
            field=models.BooleanField(default=False),
        ),
    ]
