# Generated by Django 4.0.4 on 2022-05-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_task_is_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='taskid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu.task'),
            preserve_default=False,
        ),
    ]
