# Generated by Django 4.0.4 on 2022-05-31 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_homework_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_to_send',
            field=models.BooleanField(default=False, verbose_name='Отправляемый'),
        ),
        migrations.AlterField(
            model_name='task',
            name='razdel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.razdel', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
